# Generated by Django 3.2.6 on 2021-08-06 08:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='friends',
            field=models.ManyToManyField(related_name='_sumgame_communitymember_friends_+', to='sumgame.CommunityMember'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='given_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=None, null=True), default=None, null=True, size=100),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='master_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
