# Generated by Django 3.2.6 on 2021-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumgame', '0002_auto_20210806_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='friends',
            field=models.ManyToManyField(default=None, null=True, related_name='_sumgame_communitymember_friends_+', to='sumgame.CommunityMember'),
        ),
    ]
