# Generated by Django 3.2.6 on 2021-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumgame', '0003_alter_communitymember_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='master_number_generation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
